
======= Running functional tests ======

python -m unittest discover -v 
testAdd1 (testSimple.TestAddUser) ... ok
testUnit (testSimple.TestUnit) ... Unit tests output:
test_addFail (users.tests.SimpleTest) ... ERROR
***** test_badPassword (users.tests.SimpleTest) ... ERROR
***** test_badUsername (users.tests.SimpleTest) ... ERROR
***** test_clearDatabase (users.tests.SimpleTest) ... ERROR
***** test_incorrectLogin (users.tests.SimpleTest) ... ERROR
***** test_loginFail (users.tests.SimpleTest) ... ERROR
***** test_resetFixture (users.tests.SimpleTest) ... ERROR
***** test_successfulAdd (users.tests.SimpleTest) ... ERROR
***** test_successfulCountIncrease (users.tests.SimpleTest) ... ERROR
***** test_successfulLogin (users.tests.SimpleTest) ... ERROR
***** 
***** ======================================================================
***** ERROR: test_addFail (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 22, in test_addFail
*****     Users.user_objects.assertEquals(Users.user_objects.add("add", "add"), 1)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_badPassword (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 46, in test_badPassword
*****     Users.user_objects.assertEquals(Users.user_objects.add("sdfsdfs", "CYtEuLuuutZjgQgxpeUZJUWTkOxSnSjMCpbqVlEJYHYdONIZibcTbLvRSTbRazIelzyMDMRciWJSLOXVUxiFnhmozWvQHBBFJgcYmvNeZROTSoLZQHeHYqIIzhwCdvyadfss"), -4)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_badUsername (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 42, in test_badUsername
*****     Users.user_objects.assertEquals(Users.user_objects.add("CYtEuLuuutZjgQgxpeUZJUWTkOxSnSjMCpbqVlEJYHYdONIZibcTbLvRSTbRazIelzyMDMRciWJSLOXVUxiFnhmozWvQHBBFJgcYmvNeZROTSoLZQHeHYqIIzhwCdvyas", "asdfds"), -3)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_clearDatabase (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 50, in test_clearDatabase
*****     Users_user_objects.resetFixture()
***** NameError: global name 'Users_user_objects' is not defined
***** 
***** ======================================================================
***** ERROR: test_incorrectLogin (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 38, in test_incorrectLogin
*****     Users.user_objects.assertEquals(Users.user_objects.login("add", "bcd"), -1)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_loginFail (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 18, in test_loginFail
*****     Users.user_objects.assertEquals(Users.user_objects.login("add", "add"), -1)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_resetFixok

----------------------------------------------------------------------
Ran 2 tests in 11.007s

OK
ture (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 14, in test_resetFixture
*****     Users.user_objects.assertEquals(Users_user_objects.resetFixture(), 1)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_successfulAdd (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 26, in test_successfulAdd
*****     Users.user_objects.assertEquals(Users.user_objects.add("add", "add"), -2)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_successfulCountIncrease (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 34, in test_successfulCountIncrease
*****     Users.user_objects.assertEquals(Users.user_objects.login("add", "add"), 3)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ======================================================================
***** ERROR: test_successfulLogin (users.tests.SimpleTest)
***** ----------------------------------------------------------------------
***** Traceback (most recent call last):
*****   File "/home/kevin/Documents/CS169/WarmUp1/warmup/Warmup1/users/tests.py", line 30, in test_successfulLogin
*****     Users.user_objects.assertEquals(Users.user_objects.login("add", "add"), 2)
***** AttributeError: 'UserManager' object has no attribute 'assertEquals'
***** 
***** ----------------------------------------------------------------------
***** Ran 10 tests in 10.764s
***** 
***** FAILED (errors=10)
***** 
***** Reported 10 unit tests
